import mongoose from 'mongoose';

const { Schema } = mongoose;

const MatchSchema = new Schema({
  competition: String,
  matchdate: Date,
  time: String,
  hometeam: String,
  awayteam: String,
  fthg: Number,
  ftag: Number,
  ftr: String,
  hthg: Number,
  htag: Number,
  htr: String,
  hs: Number,
  as: Number,
  hst: Number,
  ast: Number,
  hf: Number,
  af: Number,
  hc: Number,
  ac: Number,
  hy: Number,
  ay: Number,
  hr: Number,
  referee: String,
  ar: Number,
  b365h: Number,
  b365d: Number,
  b365a: Number,
  bwh: Number,
  bwd: Number,
  bwa: Number,
  iwh: Number,
  iwd: Number,
  iwa: Number,
  psh: Number,
  psd: Number,
  psa: Number,
  whh: Number,
  whd: Number,
  wha: Number,
  vch: Number,
  vcd: Number,
  vca: Number,
  maxh: Number,
  maxd: Number,
  maxa: Number,
  avgh: Number,
  avgd: Number,
  avga: Number,
  b365o25: Number,
  b365u25: Number,
  po25: Number,
  pu25: Number,
  maxo25: Number,
  maxu25: Number,
  avgo25: Number,
  avgu25: Number,
  ahh: Number,
  b365ahh: Number,
  b365aha: Number,
  pahh: Number,
  paha: Number,
  maxahh: Number,
  maxaha: Number,
  avgahh: Number,
  avgaha: Number,
  b365ch: Number,
  b365cd: Number,
  b365ca: Number,
  bwch: Number,
  bwcd: Number,
  bwca: Number,
  iwch: Number,
  iwcd: Number,
  iwca: Number,
  psch: Number,
  pscd: Number,
  psca: Number,
  whch: Number,
  whcd: Number,
  whca: Number,
  vcch: Number,
  vccd: Number,
  vcca: Number,
  maxch: Number,
  maxcd: Number,
  maxca: Number,
  avgch: Number,
  avgcd: Number,
  avgca: Number,
  b365co25: Number,
  b365cu25: Number,
  pco25: Number,
  pcu25: Number,
  maxco25: Number,
  maxcu25: Number,
  avgc025: Number,
  avgcu25: Number,
  ahch: Number,
  b365cahh: Number,
  b365caha: Number,
  pcahh: Number,
  pcaha: Number,
  maxcahh: Number,
  maxcaha: Number,
  avgcahh: Number,
  avgcaha: Number,
});

MatchSchema.index({
  competition: 1, matchdate: 1, hometeam: 1, awayteam: 1,
}, { unique: true });

export default mongoose.model('matches', MatchSchema);
